language: node_js
node_js:
- node
branches:
  only:
  - master
  - develop
before_install:
- openssl aes-256-cbc -K $encrypted_145994cb6267_key -iv $encrypted_145994cb6267_iv
  -in environment.prod.ts.enc -out src/environments/environment.prod.ts -d
before_script: ".travis/before_script.sh"
script:
- npm run build -- --prod
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./.travis/after_success.sh; fi
